// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAeIXKOpcNjRWwqjuKWbD0eAURdT3gYw',
    appId: '1:42958190461:web:e00cb4dc82230d1336fe14',
    messagingSenderId: '42958190461',
    projectId: 'chat-app-test-56193',
    authDomain: 'chat-app-test-56193.firebaseapp.com',
    storageBucket: 'chat-app-test-56193.appspot.com',
    measurementId: 'G-SVP2T304CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqdsMWEo7-sES0JDLIuWaUkqkX36rlHE',
    appId: '1:42958190461:android:fbcb7f1f2da5842236fe14',
    messagingSenderId: '42958190461',
    projectId: 'chat-app-test-56193',
    storageBucket: 'chat-app-test-56193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBauLSnpSQIMrYYVVnxnuo2P1Ahj0OSjSE',
    appId: '1:42958190461:ios:1f6a98101dcdbfa536fe14',
    messagingSenderId: '42958190461',
    projectId: 'chat-app-test-56193',
    storageBucket: 'chat-app-test-56193.appspot.com',
    iosBundleId: 'com.example.scholarChatTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBauLSnpSQIMrYYVVnxnuo2P1Ahj0OSjSE',
    appId: '1:42958190461:ios:eb96f8002f7c795636fe14',
    messagingSenderId: '42958190461',
    projectId: 'chat-app-test-56193',
    storageBucket: 'chat-app-test-56193.appspot.com',
    iosBundleId: 'com.example.scholarChatTest1.RunnerTests',
  );
}
